apiVersion: apps/v1
kind: Deployment
metadata:
  name: crocodile-deployment
  labels:
    app: crocodile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crocodile
  template:
    metadata:
      labels:
        app: crocodile
    spec:
      containers:
        - name: crocodile
          image: brandiqa/crocodile-api
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: crocodile-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector:
    app: crocodile
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
